Update lz4 default branch in rebar.config
LookingGlass fails to install using rebar3 because the "master" branch does not exist anymore. Fails with:

```
error: pathspec 'origin/master' did not match any file(s) known to git
```